/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package b1.View;

import java.net.URI;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author DELL
 */
public class GiaoDien extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDien
     */
    public GiaoDien() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cửa hàng AIR Dunk");
        Image icon = new ImageIcon(this.getClass().getResource("/logohd.png")).getImage();
        this.setIconImage(icon);

    }
    int ngang = 200;
    int doc = 954;

    public void open() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < ngang; i++) {
                    menube.setSize(doc, ngang);
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menube = new javax.swing.JPanel();
        back9 = new b1.View.chucnang.back();
        tabsanpham2 = new javax.swing.JLabel();
        tabbanhang2 = new javax.swing.JLabel();
        tabhoadon2 = new javax.swing.JLabel();
        tabkhachhang2 = new javax.swing.JLabel();
        tabthongke2 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tabthongke3 = new javax.swing.JLabel();
        tabthongke4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Menu = new b1.View.chucnang.back();
        jLabel23 = new javax.swing.JLabel();
        giaodienbanner = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);

        menube.setBackground(new java.awt.Color(255, 255, 255));

        tabsanpham2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tabsanpham2.setForeground(new java.awt.Color(255, 255, 255));
        tabsanpham2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1/khoanh/box.png"))); // NOI18N
        tabsanpham2.setText("   SẢN PHẨM");
        tabsanpham2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabsanpham2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sanphamMouseClicked(evt);
            }
        });

        tabbanhang2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tabbanhang2.setForeground(new java.awt.Color(255, 255, 255));
        tabbanhang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1/khoanh/online-shopping.png"))); // NOI18N
        tabbanhang2.setText("   BÁN HÀNG");
        tabbanhang2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabbanhang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BanhangMouseClicked(evt);
            }
        });

        tabhoadon2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tabhoadon2.setForeground(new java.awt.Color(255, 255, 255));
        tabhoadon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1/khoanh/bill.png"))); // NOI18N
        tabhoadon2.setText("   HÓA ĐƠN");
        tabhoadon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabhoadon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoadonMouseClicked(evt);
            }
        });

        tabkhachhang2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tabkhachhang2.setForeground(new java.awt.Color(255, 255, 255));
        tabkhachhang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1/khoanh/client.png"))); // NOI18N
        tabkhachhang2.setText("   KHÁCH HÀNG");
        tabkhachhang2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabkhachhang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachhangMouseClicked(evt);
            }
        });

        tabthongke2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tabthongke2.setForeground(new java.awt.Color(255, 255, 255));
        tabthongke2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1/khoanh/analysis.png"))); // NOI18N
        tabthongke2.setText("  THỐNG KÊ");
        tabthongke2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabthongke2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongkeMouseClicked(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1/khoanh/ảnh_admin__1_-removebg-preview (1) (1) (1).png"))); // NOI18N

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("ĐĂNG TRẦN QUANG ANH");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1/khoanh/logohd be.png"))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("ADMIN");

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("ShopAIRDunk.vn.com");

        tabthongke3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tabthongke3.setForeground(new java.awt.Color(255, 255, 255));
        tabthongke3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1/khoanh/sell.png"))); // NOI18N
        tabthongke3.setText("   PHIẾU GIẢM GIÁ");
        tabthongke3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabthongke3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabthongke3thongkeMouseClicked(evt);
            }
        });

        tabthongke4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tabthongke4.setForeground(new java.awt.Color(255, 255, 255));
        tabthongke4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1/khoanh/icons8-administrator-male-26.png"))); // NOI18N
        tabthongke4.setText("    NHÂN VIÊN");
        tabthongke4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabthongke4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabthongke4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout back9Layout = new javax.swing.GroupLayout(back9);
        back9.setLayout(back9Layout);
        back9Layout.setHorizontalGroup(
            back9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(back9Layout.createSequentialGroup()
                .addGroup(back9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(back9Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(back9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabkhachhang2)
                            .addComponent(tabthongke2)
                            .addComponent(tabthongke3)
                            .addGroup(back9Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel30))
                            .addComponent(tabthongke4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabsanpham2)
                            .addComponent(tabhoadon2)
                            .addComponent(tabbanhang2)))
                    .addGroup(back9Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel29))
                    .addGroup(back9Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(back9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel28)))
                    .addGroup(back9Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel32)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        back9Layout.setVerticalGroup(
            back9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel30)
                .addGap(62, 62, 62)
                .addComponent(tabbanhang2)
                .addGap(45, 45, 45)
                .addComponent(tabhoadon2)
                .addGap(43, 43, 43)
                .addComponent(tabsanpham2)
                .addGap(48, 48, 48)
                .addComponent(tabthongke3)
                .addGap(46, 46, 46)
                .addComponent(tabkhachhang2)
                .addGap(49, 49, 49)
                .addComponent(tabthongke2)
                .addGap(51, 51, 51)
                .addComponent(tabthongke4)
                .addGap(50, 50, 50)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(1, 1, 1)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1/khoanh/logohd be.png"))); // NOI18N

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        giaodienbanner.setBackground(new java.awt.Color(255, 255, 255));
        giaodienbanner.setPreferredSize(new java.awt.Dimension(1210, 686));
        giaodienbanner.setRequestFocusEnabled(false);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1/khoanh/banner (1).png"))); // NOI18N

        javax.swing.GroupLayout giaodienbannerLayout = new javax.swing.GroupLayout(giaodienbanner);
        giaodienbanner.setLayout(giaodienbannerLayout);
        giaodienbannerLayout.setHorizontalGroup(
            giaodienbannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, giaodienbannerLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        giaodienbannerLayout.setVerticalGroup(
            giaodienbannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(giaodienbannerLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 416, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1/khoanh/icons8-close-30.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1417, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(giaodienbanner, javax.swing.GroupLayout.PREFERRED_SIZE, 1462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(954, 954, 954))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(giaodienbanner, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menubeLayout = new javax.swing.GroupLayout(menube);
        menube.setLayout(menubeLayout);
        menubeLayout.setHorizontalGroup(
            menubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubeLayout.createSequentialGroup()
                .addComponent(back9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        menubeLayout.setVerticalGroup(
            menubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubeLayout.createSequentialGroup()
                .addGroup(menubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(back9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 934, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menube, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongkeMouseClicked
        // TODO add your handling code here:
        thongke tk = new thongke();
        giaodienbanner.removeAll();
        giaodienbanner.add(tk).setVisible(true);
    }//GEN-LAST:event_thongkeMouseClicked

    private void khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachhangMouseClicked
        // TODO add your handling code here:
        khachhang kh = new khachhang();
        giaodienbanner.removeAll();
        giaodienbanner.add(kh).setVisible(true);
    }//GEN-LAST:event_khachhangMouseClicked

    private void hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoadonMouseClicked
        // TODO add your handling code here:
        hoadon hd = new hoadon();
        giaodienbanner.removeAll();
        giaodienbanner.add(hd).setVisible(true);
    }//GEN-LAST:event_hoadonMouseClicked

    private void BanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanhangMouseClicked
        // TODO add your handling code here:
        banhhang bh = new banhhang();
        giaodienbanner.removeAll();
        giaodienbanner.add(bh).setVisible(true);
    }//GEN-LAST:event_BanhangMouseClicked

    private void sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sanphamMouseClicked
        // TODO add your handling code here:
        sanpham sp = new sanpham();
        giaodienbanner.removeAll();
        giaodienbanner.add(sp).setVisible(true);
    }//GEN-LAST:event_sanphamMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tabthongke3thongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabthongke3thongkeMouseClicked
        // TODO add your handling code here:
        giamgia gg = new giamgia();
        giaodienbanner.removeAll();
        giaodienbanner.add(gg).setVisible(true);
    }//GEN-LAST:event_tabthongke3thongkeMouseClicked

    private void tabthongke4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabthongke4MouseClicked
        // TODO add your handling code here:
        nhanvien nv = new nhanvien();
        giaodienbanner.removeAll();
        giaodienbanner.add(nv).setVisible(true);
    }//GEN-LAST:event_tabthongke4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private b1.View.chucnang.back Menu;
    private b1.View.chucnang.back back9;
    private javax.swing.JPanel giaodienbanner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menube;
    private javax.swing.JLabel tabbanhang2;
    private javax.swing.JLabel tabhoadon2;
    private javax.swing.JLabel tabkhachhang2;
    private javax.swing.JLabel tabsanpham2;
    private javax.swing.JLabel tabthongke2;
    private javax.swing.JLabel tabthongke3;
    private javax.swing.JLabel tabthongke4;
    // End of variables declaration//GEN-END:variables

}
